apiVersion: apps/v1
kind: Deployment
metadata:
  name: netatmo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: netatmo-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: netatmo-exporter
    spec:
      containers:
      - name: netatmo-exporter
        image: registry.gitlab.com/countsheep123/netatmo-exporter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:18080"
        - name: METRICS_ENDPOINT
          value: "/metrics"
        - name: NETATMO_REFRESH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: netatmo-exporter
              key: netatmo.refresh_token
        - name: NETATMO_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: netatmo-exporter
              key: netatmo.client_id
        - name: NETATMO_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: netatmo-exporter
              key: netatmo.client_secret
---
apiVersion: v1
kind: Service
metadata:
  name: netatmo-exporter
spec:
  clusterIP: None
  selector:
    name: netatmo-exporter
  ports:
  - name: netatmo-exporter
    protocol: TCP
    port: 18080
    targetPort: 18080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netatmo-exporter
data:
  netatmo.refresh_token: ""
  netatmo.client_id: ""
  netatmo.client_secret: ""